export default {
  ARTISTS_FETCH_DATA: 'artists/FETCH_DATA',
  ARTISTS_CLEAR_DATA: 'artists/CLEAR_DATA',
  ARTISTS_SET_PAGE: 'artists/SET_PAGE',
  ARTISTS_RESET_ERRORS: 'artists/RESET_ERRORS',
  ARTISTS_RESET_LOADERS: 'artists/RESET_LOADERS',
  LIKES_ADD_ARTIST: 'likes/ADD_ARTIST',
  LIKES_DELETE_ARTIST: 'likes/DELETE_ARTIST',
};
